name = "Cogs of Chaos"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dff1909a125b90d739df18eeaf414e46b3009a8ac1e3509223e80c27cf140a8a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
