name = "Cogs of Chaos"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3775409789e777ec6e41a1f17ccda6b9ad33d7a31cb880557a5eb855b54e8f5"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
